version: '3.3'

services:
  backend:
    build: ./backend
    networks:
      - stdnet
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - elastic
      - kibana

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      # - xpack.security.transport.ssl.enabled=false
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - stdnet
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    depends_on:
      - elastic
    image: docker.elastic.co/kibana/kibana:8.7.0
    networks:
      - stdnet
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_HOSTS=http://elastic:9200

networks:
  stdnet: