version: '3.3'

services:
  backend:
    depends_on:
      - kibana
    build: ./backend
    networks:
      - stdnet
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3000:3000
    env_file:
      - .env

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      # - xpack.security.transport.ssl.enabled=false
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - stdnet
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    depends_on:
      - elastic
    networks:
      - stdnet
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - ENTERPRISESEARCH_HOST=http://enterprise:3002
    healthcheck:
      test:
        [
            "CMD-SHELL",
            "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

networks:
  stdnet: