version: '3.3'

services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - elastic
      - kibana

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    depends_on:
      - elastic
    image: docker.elastic.co/kibana/kibana:8.7.0
    networks:
      - elastic
    ports:
      - 5601:5601

networks:
  elastic: